/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlanMyTripRouteImport } from './routes/plan-my-trip'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesSlugRouteImport } from './routes/packages/$slug'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations/$slug'
import { Route as AdventuresSlugRouteImport } from './routes/adventures/$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanMyTripRoute = PlanMyTripRouteImport.update({
  id: '/plan-my-trip',
  path: '/plan-my-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const AdventuresSlugRoute = AdventuresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdventuresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/plan-my-trip': typeof PlanMyTripRoute
  '/search': typeof SearchRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/plan-my-trip': typeof PlanMyTripRoute
  '/search': typeof SearchRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adventures': typeof AdventuresRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/guides': typeof GuidesRoute
  '/journal': typeof JournalRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/plan-my-trip': typeof PlanMyTripRoute
  '/search': typeof SearchRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adventures'
    | '/contact'
    | '/destinations'
    | '/guides'
    | '/journal'
    | '/packages'
    | '/plan-my-trip'
    | '/search'
    | '/adventures/$slug'
    | '/destinations/$slug'
    | '/journal/$slug'
    | '/packages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adventures'
    | '/contact'
    | '/destinations'
    | '/guides'
    | '/journal'
    | '/packages'
    | '/plan-my-trip'
    | '/search'
    | '/adventures/$slug'
    | '/destinations/$slug'
    | '/journal/$slug'
    | '/packages/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adventures'
    | '/contact'
    | '/destinations'
    | '/guides'
    | '/journal'
    | '/packages'
    | '/plan-my-trip'
    | '/search'
    | '/adventures/$slug'
    | '/destinations/$slug'
    | '/journal/$slug'
    | '/packages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdventuresRoute: typeof AdventuresRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  GuidesRoute: typeof GuidesRoute
  JournalRoute: typeof JournalRouteWithChildren
  PackagesRoute: typeof PackagesRouteWithChildren
  PlanMyTripRoute: typeof PlanMyTripRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-my-trip': {
      id: '/plan-my-trip'
      path: '/plan-my-trip'
      fullPath: '/plan-my-trip'
      preLoaderRoute: typeof PlanMyTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/adventures/$slug': {
      id: '/adventures/$slug'
      path: '/$slug'
      fullPath: '/adventures/$slug'
      preLoaderRoute: typeof AdventuresSlugRouteImport
      parentRoute: typeof AdventuresRoute
    }
  }
}

interface AdventuresRouteChildren {
  AdventuresSlugRoute: typeof AdventuresSlugRoute
}

const AdventuresRouteChildren: AdventuresRouteChildren = {
  AdventuresSlugRoute: AdventuresSlugRoute,
}

const AdventuresRouteWithChildren = AdventuresRoute._addFileChildren(
  AdventuresRouteChildren,
)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdventuresRoute: AdventuresRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  GuidesRoute: GuidesRoute,
  JournalRoute: JournalRouteWithChildren,
  PackagesRoute: PackagesRouteWithChildren,
  PlanMyTripRoute: PlanMyTripRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
